### ISSUE TITLE
Flowmap.blue sometimes doesn't load on iOS 

### ISSUE THREAD

**Issue by LeLunZ** [FlowmapBlue/FlowmapBlue#49]
On iOS the homepage of flowmap.blue doesnt seem to load.

For me it happened in multiple browsers. But I also couldn't reproduce it after it happened.
If it happens it hangs in this screen:

![IMG_0320](https://user-images.githubusercontent.com/31982496/143453427-3de709e4-716e-46e0-ad88-d9b149c516ae.PNG)

**Comment by ilyabo** [comment]
Thanks for reporting! I've seen this a few times too. The page seems to load actually, but the styles are broken. All the content is white. I made some changes, hopefully, this will go away. Let me know if you experience this again.
