### ISSUE TITLE
Failing to load properties sheet: "Oops… The properties sheet could not be loaded: Failed to fetch"

### ISSUE THREAD

**Issue by dirk87** [FlowmapBlue/FlowmapBlue#84]
Getting this error where the properties sheet is failing to load. Do any others have a tip on how to sort this out, please?

Oops… The properties sheet could not be loaded:
Failed to fetch

**Comment by ilyabo** [comment]
Hello @dirk87! Did you share you spreadsheet as [described here](https://flowmap.blue/how-to-make-a-flow-map) in Step 4?

**Comment by dirk87** [comment]
Hi Ilya

thanks for your email.

I thought I had done step 4 but upon checking, I had clearly not done that!

It is working now.
<https://flowmap.blue/1D9Ym2KUxze5ayR41bpGu7pzpR6WdBJ0blU47qv0UuqA/8693eac?v=-33.932466%2C18.445416%2C9.28%2C0%2C0&a=0&as=1&b=1&bo=75&c=1&ca=1&d=1&fe=1&lt=1&lfm=ALL&col=Default&f=50>

Thanks
Dirk du Preez
